# Project Euler 29: How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 
# and 2 ≤ b ≤ 100?

from math import pow

def compute():
    result_set = set()
    ans = 0
    for a in range(2, 101):
        for b in range(2, 101):
            ans = pow(a,b)
            result_set.add(ans)
    return str(len(result_set))        

if __name__ == "__main__":
    print(compute())