# Project Euler 29: How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 
# and 2 ≤ b ≤ 100?

def compute():
    result_set = set()
    for a in range(2, 101):
        for b in range(2, 101):
            result_set.add(a**b)
    return str(len(result_set))        

if __name__ == "__main__":
    print(compute())