'''
Project Euler 45: After 40755, what is the next triangle number that is also pentagonal and hexagonal?

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle		Tn=n(n+1)/2		1, 3, 6, 10, 15, …
Pentagonal		Pn=n(3n-1)/2		1, 5, 12, 22, 35, …
Hexagonal		Hn=n(2n-1)		1, 6, 15, 28, 45, …

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

Note: All hexagonal numbers must be triangular numbers as well; there is no need to check for triangularity.
'''

import time

t1 = time.time()

def is_pentagonal(n):
    return (1+(1+24*n)**0.5)/6 == int((1+(1+24*n)**0.5)/6)

def is_hexagonal(n):
    return n*(2*n - 1)

n = 144
while not is_pentagonal(is_hexagonal(n)):
    n += 1
print(is_hexagonal(n))
    
t2 = time.time()
print("Time elapsed:", t2 - t1, "seconds")